/**
 * The intensity axis: how loud the palette's hues are.
 *
 * The fifth appearance axis, and the mirror image of the contrast one. A contrast
 * level restates the *neutrals* — grounds, surfaces, text, boundaries — and may
 * never touch a hue; an intensity restates the *hues* — the accent, the second
 * accent, the verdicts, the categorical wheel — and may never touch a neutral.
 * Between them they cover the palette without either being able to undo the
 * other, which is why they compose rather than multiply into a matrix of themes.
 *
 * ## Why it exists
 *
 * Twelve categorical hues plus four meanings is a lot of colour, and how much of
 * it a person wants is not a question the app can answer for them. The same
 * screen that reads as helpfully colour-coded to one learner reads as busy to
 * another, and both were previously served by one compromise. This is that
 * compromise made adjustable, without forking a palette: Indigo Calm and Indigo
 * Vivid are the same palette at two volumes, not two palettes to keep in step.
 *
 * ## Why it lives in the palette files
 *
 * A CSS custom property cannot refer to itself, so `--color-accent` cannot be
 * redefined as a transformation of `--color-accent`. A contrast level escapes this
 * because it is written in terms of `ink` and `paper` — two roles it does not
 * itself set — and there is no equivalent source for a hue. The alternative would
 * be a second name for every hue in every palette, doubling the role count purely
 * to enable this axis.
 *
 * So each palette carries its own `calm` and `vivid` blocks, generated by scaling
 * chroma in OKLab and walking the scale back wherever a step would drop a role
 * under a WCAG floor. That trade is worth naming: an intensity is *not*
 * palette-agnostic the way a contrast level is, so a new palette has to generate
 * its own two blocks — and `tests/a11y/contrast.test.ts` fails until it does,
 * which is what stops a palette shipping with one volume.
 *
 * Every level is a level a learner can pick, so every level is held to AA: the
 * test checks each palette against each contrast level × each intensity.
 */

import { defineAxis } from './appearance';

export const INTENSITIES = ['calm', 'normal', 'vivid'] as const;
export type Intensity = (typeof INTENSITIES)[number];

export const DEFAULT_INTENSITY: Intensity = 'normal';

export interface IntensityOption {
  readonly id: Intensity;
  /** Shown in the control; the full label is the accessible name. */
  readonly shortLabel: string;
  readonly label: string;
}

export const INTENSITY_OPTIONS: readonly IntensityOption[] = [
  { id: 'calm', shortLabel: 'Calm', label: 'Calm colour' },
  { id: 'normal', shortLabel: 'Normal', label: 'Normal colour' },
  { id: 'vivid', shortLabel: 'Vivid', label: 'Vivid colour' },
];

export const INTENSITY_AXIS = defineAxis({
  key: 'intensity',
  values: INTENSITIES,
  fallback: DEFAULT_INTENSITY,
});

export const INTENSITY_STORAGE_KEY = INTENSITY_AXIS.storageKey;
export const isIntensity = INTENSITY_AXIS.is;
export const applyIntensity = INTENSITY_AXIS.apply;
