import type { MissionDefinition } from '../domain/missions';

/**
 * The first authored communicative journey.
 *
 * These are sequencing records over passages the pack already owns. Adding a
 * mission never creates a second copy of a sentence and never stores an
 * exercise. A future pack-supplied curriculum can implement the same shape.
 */
export const MISSIONS: readonly MissionDefinition[] = [
  /**
   * The first mission is the one an adult actually needs first, and "hello,
   * how are you, goodbye" is not it: that exchange is over in four turns and
   * leaves you standing there. So the four greeting dialogues carry on past
   * the wellbeing answer into the conversation that really happens — where you
   * are from, where you live now, whether you like it, what you do, what you
   * do with your time — and every one of those moves has a palette of natural
   * alternatives behind it rather than one prescribed sentence.
   *
   * The asking palettes are the half that makes it a conversation. A learner
   * who can only answer is still being interviewed.
   */
  {
    id: 'greet-and-respond',
    language: 'es',
    level: 'a1',
    order: 0,
    title: 'Meet someone and keep talking',
    goal: 'Greet someone, say where you are from and what you do, ask them back, and keep the conversation going.',
    passage: '700033',
    transfers: [
      {
        passage: '700034',
        support: 'guided',
        brief: 'A friend you do not know well yet — work, the weekend, and where you are from.',
      },
      {
        passage: '700035',
        support: 'guided',
        brief: 'The same conversation at work, in usted throughout.',
      },
      {
        passage: '700036',
        support: 'independent',
        brief: 'Meet a new neighbour and do the asking yourself, from intention cues.',
      },
    ],
    capabilities: [
      'greet-someone',
      'respond-to-wellbeing',
      'ask-about-origin',
      'say-where-youre-from',
      'say-where-you-are-based',
      'say-if-you-like-a-place',
      'ask-what-someone-does',
      'say-what-you-do',
      'ask-about-free-time',
      'talk-about-free-time',
      'close-friendly-exchange',
    ],
    responsePalettes: [
      {
        id: 'wellbeing-answer',
        capability: 'respond-to-wellbeing',
        title: 'More than “I’m fine”',
        cue: 'Answer naturally according to how you feel. Add “¿Y tú?” or “¿Y usted?” when it fits.',
        initiallyVisible: 3,
        responses: [
          { item: '000709', nuance: 'Neutral and dependable' },
          { item: '000728', nuance: 'Enthusiastic and very positive' },
          { item: '000729', nuance: 'Casual and concise' },
          { item: '000730', nuance: 'Positive, but understated' },
          { item: '000731', nuance: 'So-so; neither good nor bad' },
          { item: '000732', nuance: 'Things could be better' },
          { item: '000791', nuance: 'A little tired · masculine speaker' },
          { item: '000733', nuance: 'Tired · feminine speaker' },
          { item: '000734', nuance: 'A gently softened sad answer' },
          { item: '000735', nuance: 'Clearly not doing well' },
        ],
      },
      {
        id: 'origin-answer',
        capability: 'say-where-youre-from',
        title: 'Where you are from — and where you live',
        cue: 'Name the country, the city, or your nationality. Add where you live now when the two differ.',
        initiallyVisible: 3,
        responses: [
          { item: '001015', nuance: 'The shortest complete answer' },
          { item: '000986', nuance: 'From one place, living in another' },
          { item: '001016', nuance: 'Nationality first, then the city' },
          { item: '001017', nuance: 'Places an unknown town next to a known one' },
          { item: '001018', nuance: 'Your family’s origin, not your own' },
          { item: '001019', nuance: 'Where you were born, with nací' },
          { item: '001020', nuance: 'For when you have moved away' },
          { item: '001021', nuance: 'When the place needs no name' },
        ],
      },
      {
        id: 'living-here',
        capability: 'say-where-you-are-based',
        title: 'Do you live here?',
        cue: 'Say the country, the city, the area or how long — whichever the question is really asking.',
        initiallyVisible: 3,
        responses: [
          { item: '001022', nuance: 'How long, with desde hace' },
          { item: '001023', nuance: 'Living here, working elsewhere' },
          { item: '001024', nuance: 'Only visiting' },
          { item: '001025', nuance: 'Answers with a distance' },
          { item: '000862', nuance: 'Living here, from somewhere else' },
          { item: '000857', nuance: 'The area and the kind of home' },
          { item: '000859', nuance: 'Outside the city' },
          { item: '000864', nuance: 'How long in the same place' },
        ],
      },
      {
        id: 'place-feelings',
        capability: 'say-if-you-like-a-place',
        title: 'Do you like it here?',
        cue: 'Say yes, no or partly — and give the reason. A bare “sí” ends the conversation.',
        initiallyVisible: 3,
        responses: [
          { item: '000988', nuance: 'Yes, with a reason about the people' },
          { item: '001026', nuance: 'Warmer than me gusta' },
          { item: '001027', nuance: 'Positive, with an honest reservation' },
          { item: '001028', nuance: 'Describes the place, not your feeling' },
          { item: '001029', nuance: 'Says what living there costs you' },
          { item: '001030', nuance: 'Honest and negative, without rudeness' },
          { item: '001031', nuance: 'A clear no, with a reason' },
          { item: '001032', nuance: 'Two concrete reasons' },
        ],
      },
      {
        id: 'what-you-do',
        capability: 'say-what-you-do',
        title: 'What you do',
        cue: 'Name the job, or the place, or who you do it with — whatever is true today.',
        initiallyVisible: 3,
        responses: [
          { item: '000990', nuance: 'The job, then where' },
          { item: '000849', nuance: 'The job before the place' },
          { item: '000850', nuance: 'Adds who you work with' },
          { item: '000851', nuance: 'For someone studying as well' },
          { item: '000852', nuance: 'Where rather than what' },
          { item: '000853', nuance: 'Honest, when you are between jobs' },
          { item: '000854', nuance: 'Adds how near it is' },
          { item: '000855', nuance: 'Says more than the question asked' },
          { item: '000856', nuance: 'A precise job · feminine speaker' },
        ],
      },
      {
        id: 'free-time',
        capability: 'talk-about-free-time',
        title: 'What you do with your time',
        cue: 'One activity is enough. Adding how often, when or who with is what keeps it going.',
        initiallyVisible: 3,
        responses: [
          { item: '000994', nuance: 'Two activities at once' },
          { item: '001033', nuance: 'Calm and dependable' },
          { item: '001034', nuance: 'Adds how often' },
          { item: '001035', nuance: 'Says who with, and when' },
          { item: '001036', nuance: 'A quiet answer, and a common one' },
          { item: '001037', nuance: 'Something you do for other people' },
          { item: '001038', nuance: 'Says where, and when' },
          { item: '001039', nuance: 'Honest, when the true answer is none' },
        ],
      },
      {
        id: 'asking-origin',
        capability: 'ask-about-origin',
        title: 'Asking where they are from',
        cue: 'Ask back. Pick the tú or usted form to match how they spoke to you.',
        initiallyVisible: 2,
        responses: [
          { item: '000008', nuance: 'The plain question' },
          { item: '001040', nuance: 'Returns the question' },
          { item: '001041', nuance: 'A yes-or-no opening' },
          { item: '001042', nuance: 'When you already know the country' },
          { item: '001043', nuance: 'The formal version' },
          { item: '001044', nuance: 'Where they live, not where they began' },
          { item: '001045', nuance: 'Asks how long' },
          { item: '001046', nuance: 'Widens it to their family' },
        ],
      },
      {
        id: 'asking-what-they-do',
        capability: 'ask-what-someone-does',
        title: 'Asking what they do',
        cue: 'Ask about the job, the place or the hours. Any of them opens the same subject.',
        initiallyVisible: 2,
        responses: [
          { item: '000989', nuance: 'The everyday question' },
          { item: '001047', nuance: 'The most common way to ask' },
          { item: '000105', nuance: 'The place rather than the job' },
          { item: '001048', nuance: 'Natural with someone younger' },
          { item: '001049', nuance: 'Moves to how they feel about it' },
          { item: '001050', nuance: 'The formal version' },
          { item: '001051', nuance: 'Asks about the schedule' },
          { item: '001052', nuance: 'Keeps it going without repeating yourself' },
        ],
      },
      {
        id: 'asking-free-time',
        capability: 'ask-about-free-time',
        title: 'Asking about their time',
        cue: 'The question that turns an exchange of facts into a conversation.',
        initiallyVisible: 2,
        responses: [
          { item: '000992', nuance: 'The open question' },
          { item: '001053', nuance: 'Open, and easy to answer' },
          { item: '001054', nuance: 'A yes-or-no that always goes somewhere' },
          { item: '001055', nuance: 'Anchored in time' },
          { item: '001056', nuance: 'For a livelier conversation' },
          { item: '001057', nuance: 'The formal version' },
          { item: '001058', nuance: 'Names one activity and asks about it' },
          { item: '001059', nuance: 'Offers two, so they can pick' },
        ],
      },
      {
        id: 'greeting-openers',
        capability: 'greet-someone',
        title: 'Open it',
        cue: 'Match the time of day and how well you know them. Both are carried by the greeting.',
        initiallyVisible: 3,
        responses: [
          { item: '000705', nuance: 'Your name, when they do not have it' },
          { item: '001229', nuance: 'Time of day plus an opener, in four words' },
          { item: '000713', nuance: 'The shortest one, for someone you know' },
          { item: '001230', nuance: 'Gives your name and hands the turn back' },
          { item: '000719', nuance: 'Formal, with a surname' },
          { item: '001231', nuance: 'Formal, and for after dark' },
          { item: '000724', nuance: 'For a first meeting, after they introduced themselves' },
          { item: '001232', nuance: 'Warmer than ¿cómo estás? with someone you know' },
        ],
      },
      {
        id: 'closing-well',
        capability: 'close-friendly-exchange',
        title: 'Close it',
        cue: 'Say when you will next see them if you know, and something warm if you do not.',
        initiallyVisible: 3,
        responses: [
          { item: '000711', nuance: 'The plain close, with their name' },
          { item: '001233', nuance: 'Bueno is what signals you are leaving' },
          { item: '000717', nuance: 'Sooner than hasta luego' },
          { item: '001234', nuance: 'When you know when' },
          { item: '000721', nuance: 'Formal, and wishes them the day' },
          { item: '001235', nuance: 'When you do not know when' },
          { item: '000726', nuance: 'Closes with concern for them' },
          { item: '001236', nuance: 'Warm without being long' },
        ],
      },
    ],
    spotlight: 6,
    estimatedMinutes: 18,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'the other person',
  },
  /**
   * The mission that rescues all the others.
   *
   * Every other journey here assumes the exchange goes to plan. In a real one it
   * does not: the answer comes back at full speed, with a word you have never
   * met, and the learner's own three months of vocabulary are no help at all.
   * These are the moves that buy another attempt — and they are the same four
   * whether the room is a shop, a street, a classroom or a meeting, which is why
   * this sits second rather than in whichever domain it was written for.
   *
   * Five of its palette entries are phrases the pack already shipped and nothing
   * pointed at: `¿Puedes repetir, por favor?` has been in `sentences-core` since
   * the beginning. A mission is sequencing, so gathering them costs no content.
   */
  {
    id: 'make-yourself-understood',
    language: 'es',
    level: 'a1',
    order: 1,
    title: 'Make yourself understood',
    goal: 'Say you have not understood, ask for it again or slower, find the word you need, and check you got it right.',
    passage: '700058',
    transfers: [
      {
        passage: '700059',
        support: 'guided',
        brief: 'Directions you cannot follow. Slow the other person down instead of guessing.',
      },
      {
        passage: '700060',
        support: 'guided',
        brief: 'In class, in tú, where the word itself is the problem.',
      },
      {
        passage: '700061',
        support: 'independent',
        brief: 'An address you cannot afford to get wrong. Get it in writing.',
      },
    ],
    capabilities: [
      'say-you-did-not-understand',
      'ask-to-repeat',
      'ask-to-slow-down',
      'check-you-were-understood',
    ],
    responsePalettes: [
      {
        id: 'not-understanding',
        capability: 'say-you-did-not-understand',
        title: 'Say it before you nod',
        cue: 'Nodding buys you nothing. Say which part failed — the sentence, one word, or the speed.',
        initiallyVisible: 3,
        responses: [
          { item: '001114', nuance: 'Have this one ready before any other' },
          { item: '001115', nuance: 'Softer: you caught some of it' },
          { item: '001116', nuance: 'The shortest, and very common' },
          { item: '001117', nuance: 'Explains why, so they adjust' },
          { item: '001118', nuance: 'One word, not the whole sentence' },
          { item: '001119', nuance: 'Useful at the start of a conversation' },
          { item: '001120', nuance: 'Asks for patience without demanding it' },
          { item: '001067', nuance: 'The full move: name it, then ask' },
        ],
      },
      {
        id: 'asking-again',
        capability: 'ask-to-repeat',
        title: 'Ask for it again',
        cue: 'Ask for the part you missed rather than the whole thing — you will get a clearer answer.',
        initiallyVisible: 3,
        responses: [
          { item: '001121', nuance: 'The dependable formal one' },
          { item: '000014', nuance: 'The same request in tú' },
          { item: '000405', nuance: 'Short, and works everywhere' },
          { item: '001122', nuance: 'Formal, for the whole sentence' },
          { item: '001123', nuance: 'Asks for the part you missed' },
          { item: '001124', nuance: 'Numbers are what gets missed most' },
          { item: '001125', nuance: 'For a noisy street or a bad line' },
          { item: '001085', nuance: 'Names which part to repeat' },
        ],
      },
      {
        id: 'slower-please',
        capability: 'ask-to-slow-down',
        title: 'Ask them to slow down',
        cue: 'Speed is the usual problem, not vocabulary. Asking for less is easier to grant.',
        initiallyVisible: 3,
        responses: [
          { item: '000015', nuance: 'Three words, and the most useful three there are' },
          { item: '001126', nuance: 'A full formal request' },
          { item: '001127', nuance: 'The same in tú' },
          { item: '001128', nuance: 'Puts it on your ear, not their speech' },
          { item: '001129', nuance: 'Asks for less, so it is easier to grant' },
          { item: '001130', nuance: 'When the problem is thinking, not hearing' },
          { item: '001131', nuance: 'When a whole sentence is too much at once' },
          { item: '001069', nuance: 'Slower, plus the reason why' },
        ],
      },
      {
        id: 'finding-a-word',
        capability: 'ask-for-a-word',
        title: 'Find the word you are missing',
        cue: 'You do not need the word. You need a way to ask for it without leaving Spanish.',
        initiallyVisible: 3,
        responses: [
          { item: '000017', nuance: 'The question that gets you unstuck' },
          { item: '001132', nuance: 'While pointing at something written' },
          { item: '001133', nuance: 'Says what is missing, and invites help' },
          { item: '001134', nuance: 'Asks for a simpler word, not the same one' },
          { item: '001135', nuance: 'When you can point at it' },
          { item: '001136', nuance: 'Buys a moment and keeps your turn' },
          { item: '001137', nuance: 'Checks a word you have guessed' },
          { item: '001071', nuance: 'Names the word you are asking about' },
        ],
      },
      {
        id: 'what-does-it-mean',
        capability: 'ask-what-something-means',
        title: 'Ask what it means',
        cue: 'An example is usually clearer than a definition. Ask for whichever you can use.',
        initiallyVisible: 3,
        responses: [
          { item: '000016', nuance: 'The plain question' },
          { item: '001138', nuance: 'Bare, when the word is obvious from context' },
          { item: '001139', nuance: 'For a word they said, not one you can see' },
          { item: '001140', nuance: 'A statement, when a question would interrupt' },
          { item: '001141', nuance: 'Asks for an explanation, not a translation' },
          { item: '001142', nuance: 'Often clearer than a definition' },
          { item: '001143', nuance: 'Narrows it down when nothing else works' },
          { item: '001093', nuance: 'Points at it and asks in three words' },
        ],
      },
      {
        id: 'checking-you-got-it',
        capability: 'check-you-were-understood',
        title: 'Check before you act on it',
        cue: 'Say the detail back. A wrong day or a wrong number costs more than the question does.',
        initiallyVisible: 3,
        responses: [
          { item: '001144', nuance: 'Add it after repeating what you heard' },
          { item: '001145', nuance: 'Lighter, and very common' },
          { item: '001146', nuance: 'Puts the doubt on you rather than them' },
          { item: '001147', nuance: 'The other direction: did your Spanish land' },
          { item: '001148', nuance: 'Formal, and useful at work' },
          { item: '001149', nuance: 'Announces the read-back so it is not doubt' },
          { item: '001150', nuance: 'Reads back the detail that matters' },
          { item: '001111', nuance: 'The whole detail, then the check' },
        ],
      },
      {
        id: 'in-writing',
        capability: 'ask-it-in-writing',
        title: 'Get it in writing',
        cue: 'An address or a time heard once is lost. Reading is far easier than listening.',
        initiallyVisible: 3,
        responses: [
          { item: '001151', nuance: 'An address heard once is an address lost' },
          { item: '001152', nuance: 'For a phone number or a price' },
          { item: '001153', nuance: 'For an appointment' },
          { item: '001154', nuance: 'A street name is hard to hear, easy to read' },
          { item: '001155', nuance: 'You do the writing, and they wait' },
          { item: '001156', nuance: 'Prices in a foreign language go by fast' },
          { item: '001157', nuance: 'The tú version, for a friend or classmate' },
          { item: '001077', nuance: 'Names exactly which detail to write' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 14,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'the other person',
  },
  {
    id: 'cafe-order',
    language: 'es',
    level: 'a1',
    order: 2,
    title: 'Order at a café',
    goal: 'Order a drink, add something else and understand the price.',
    passage: '700009',
    transfers: [
      {
        passage: '700015',
        support: 'guided',
        brief: 'Order a different drink and respond when the waiter suggests an extra.',
      },
      {
        passage: '700021',
        support: 'guided',
        brief: 'Change the order, decline one option and ask for the new total.',
      },
      {
        passage: '700022',
        support: 'independent',
        brief: 'Handle a breakfast order from intention cues, without a line-by-line script.',
      },
    ],
    capabilities: [
      'order-food-drink',
      'handle-add-on',
      'ask-understand-price',
      'close-service-exchange',
    ],
    responsePalettes: [
      {
        id: 'cafe-order-choice',
        capability: 'order-food-drink',
        title: 'Build the order you actually want',
        cue: 'Order a drink naturally. Change the drink, milk, sugar or quantity to fit your choice.',
        initiallyVisible: 3,
        responses: [
          { item: '000739', nuance: 'Short, polite and direct' },
          { item: '000740', nuance: 'A dependable full request with quiero' },
          { item: '000741', nuance: 'Natural when ordering in a group' },
          { item: '000742', nuance: 'A common way to make your choice' },
          { item: '000743', nuance: 'A minimal everyday order' },
          { item: '000744', nuance: 'Remove an ingredient with sin' },
          { item: '000745', nuance: 'Add a preference with pero' },
          { item: '000746', nuance: 'Leave room to order more later' },
        ],
      },
      {
        id: 'add-on-answer',
        capability: 'handle-add-on',
        title: 'Yes, no, or yes-but',
        cue: '“¿Algo más?” always comes. Decide, and say it in one move.',
        initiallyVisible: 3,
        responses: [
          { item: '000559', nuance: 'Yes, and asks the price in the same breath' },
          { item: '001158', nuance: 'A complete, polite no' },
          { item: '000596', nuance: 'No, and names what you are keeping' },
          { item: '001159', nuance: 'Adds a second thing without repeating the first' },
          { item: '000631', nuance: 'Yes, with an ingredient removed' },
          { item: '001160', nuance: 'The shortest way to close the order' },
          { item: '001161', nuance: 'Says yes and sets the size' },
          { item: '000637', nuance: 'Yes, then straight to the total' },
        ],
      },
      {
        id: 'understanding-the-price',
        capability: 'ask-understand-price',
        title: 'Ask what it comes to',
        cue: 'Before you order, or after. Ask for one item or the lot.',
        initiallyVisible: 3,
        responses: [
          { item: '001162', nuance: 'For the whole order rather than one item' },
          { item: '001163', nuance: 'Asks about one thing before ordering it' },
          { item: '000278', nuance: 'Asks for the total to be brought to you' },
          { item: '000277', nuance: 'Worth asking before you order in a small place' },
          { item: '001164', nuance: 'For the extra rather than the drink' },
          { item: '001165', nuance: 'When you missed the number the first time' },
          { item: '000559', nuance: 'Folded into accepting the extra' },
          { item: '000637', nuance: 'Asks for the total of everything' },
        ],
      },
      {
        id: 'closing-the-order',
        capability: 'close-service-exchange',
        title: 'Leave well',
        cue: 'A bare “gracias” works. These cost one more word and land better.',
        initiallyVisible: 3,
        responses: [
          { item: '000561', nuance: 'The bare minimum, and it is enough' },
          { item: '001166', nuance: 'Warmer than gracias on its own' },
          { item: '001167', nuance: 'The everyday close' },
          { item: '000598', nuance: 'Handing something over as you go' },
          { item: '001168', nuance: 'Says the service was good' },
          { item: '000633', nuance: 'Agreeing and paying in one line' },
          { item: '001169', nuance: 'A compliment on the way out' },
          { item: '000639', nuance: 'The full close, with a goodbye' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 10,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the waiter',
  },
  {
    id: 'ask-directions',
    language: 'es',
    level: 'a1',
    order: 3,
    title: 'Ask for directions',
    goal: 'Ask where a place is and follow a short answer.',
    passage: '700011',
    transfers: [
      {
        passage: '700016',
        support: 'guided',
        brief: 'Find a different place and check how far away it is.',
      },
      {
        passage: '700023',
        support: 'guided',
        brief: 'Ask for the museum and follow a route with two landmarks.',
      },
      {
        passage: '700024',
        support: 'independent',
        brief: 'Find a bus stop from intention cues and confirm the distance.',
      },
    ],
    capabilities: [
      'ask-for-directions',
      'follow-simple-directions',
      'check-distance',
      'thank-for-help',
    ],
    responsePalettes: [
      {
        id: 'directions-destination',
        capability: 'ask-for-directions',
        title: 'More than one way to ask the way',
        cue: 'Ask for the place or route you need. Choose a direct, indirect or destination-first question.',
        initiallyVisible: 3,
        responses: [
          { item: '000747', nuance: 'Polite and direct' },
          { item: '000748', nuance: 'Slightly more formal with disculpe' },
          { item: '000749', nuance: 'Put the courtesy at the end' },
          { item: '000750', nuance: 'State what you are looking for' },
          { item: '000751', nuance: 'Soften the request with an indirect question' },
          { item: '000752', nuance: 'Ask for a route, not only a location' },
          { item: '000753', nuance: 'Check whether a known place is nearby' },
          { item: '000754', nuance: 'Explain the destination, then ask which way' },
        ],
      },
      {
        id: 'following-directions',
        capability: 'follow-simple-directions',
        title: 'Check you followed it',
        cue: 'The answer comes fast. Read one step back rather than nodding at all four.',
        initiallyVisible: 3,
        responses: [
          { item: '001170', nuance: 'Offers both, so the answer cannot be vague' },
          { item: '001171', nuance: 'Reads back the first half' },
          { item: '000642', nuance: 'Places it against a landmark you know' },
          { item: '001172', nuance: 'Asks for the next step only' },
          { item: '001173', nuance: 'The detail most often missed' },
          { item: '000649', nuance: 'Confirms where the turn happens' },
          { item: '001174', nuance: 'When you have the direction but not the place' },
          { item: '001175', nuance: 'Names a landmark to confirm the route' },
        ],
      },
      {
        id: 'how-far',
        capability: 'check-distance',
        title: 'Find out how far',
        cue: '“Cerca” means different things on foot and in a car. Ask for a number.',
        initiallyVisible: 3,
        responses: [
          { item: '000313', nuance: 'The plain question' },
          { item: '001176', nuance: 'Asks for a number instead of a feeling' },
          { item: '001177', nuance: 'The question behind the question' },
          { item: '000601', nuance: 'Names the place you are asking about' },
          { item: '001178', nuance: 'Asks for a recommendation, not just a distance' },
          { item: '000571', nuance: 'Word order that puts the place last' },
          { item: '000644', nuance: 'Anchors it to where you are standing' },
          { item: '000651', nuance: 'Proposes a number and lets them correct it' },
        ],
      },
      {
        id: 'thanking-for-help',
        capability: 'thank-for-help',
        title: 'Thank them properly',
        cue: 'Someone stopped for you. One word more than gracias is what shows it.',
        initiallyVisible: 3,
        responses: [
          { item: '000573', nuance: 'The dependable two words' },
          { item: '001179', nuance: 'Formal and warm' },
          { item: '000603', nuance: 'Signals you understood as well as heard' },
          { item: '001180', nuance: 'Confirms the help actually worked' },
          { item: '000646', nuance: 'Names what you are thanking them for' },
          { item: '001181', nuance: 'Short, when you are already moving' },
          { item: '000653', nuance: 'Says explicitly that you have got it' },
          { item: '001182', nuance: 'For someone who went out of their way' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 9,
    learnerSpeaker: 'Turista',
    scenarioPartner: 'a local person',
  },
  {
    id: 'shop-clothes',
    language: 'es',
    level: 'a1',
    order: 4,
    title: 'Shop for clothes',
    goal: 'Ask for help, choose an item and handle the fitting-room exchange.',
    passage: '700010',
    transfers: [
      {
        passage: '700017',
        support: 'guided',
        brief: 'Choose a different item, size and colour.',
      },
      {
        passage: '700025',
        support: 'guided',
        brief: 'Ask for trousers, try them on and decide whether to buy them.',
      },
      {
        passage: '700026',
        support: 'independent',
        brief: 'Handle a shoe purchase from intention cues, including size and price.',
      },
    ],
    capabilities: [
      'seek-clothing-item',
      'handle-clothing-size',
      'ask-to-try-on',
      'choose-clothing-purchase',
      'ask-understand-item-price',
    ],
    responsePalettes: [
      {
        id: 'clothing-request',
        capability: 'seek-clothing-item',
        title: 'Shop by item, colour, fit or purpose',
        cue: 'Tell the assistant what you need—or politely say that you are only looking.',
        initiallyVisible: 3,
        responses: [
          { item: '000755', nuance: 'Name an item and colour' },
          { item: '000756', nuance: 'Use quiero for a direct choice' },
          { item: '000757', nuance: 'Use necesito when it is a need' },
          { item: '000758', nuance: 'Use estoy buscando for an ongoing search' },
          { item: '000759', nuance: 'Keep the item and change its colour' },
          { item: '000760', nuance: 'Ask for a different fit' },
          { item: '000761', nuance: 'Politely decline help' },
          { item: '000762', nuance: 'Describe quality and purpose instead of an item' },
        ],
      },
      {
        id: 'your-size',
        capability: 'handle-clothing-size',
        title: 'Answer the size question',
        cue: 'Sizes differ by country. Guessing out loud is normal, and better than silence.',
        initiallyVisible: 3,
        responses: [
          { item: '000565', nuance: 'Honest, and asks to try instead' },
          { item: '001183', nuance: 'When you know the local number' },
          { item: '001184', nuance: 'Sizes differ by country, and saying so is normal' },
          { item: '000607', nuance: 'The same for a masculine item' },
          { item: '000297', nuance: 'Asks the assistant rather than the shelf' },
          { item: '001185', nuance: 'Hedged, when you are guessing' },
          { item: '000657', nuance: 'Gives the number and moves straight on' },
          { item: '000664', nuance: 'Shoe sizes, which use número not talla' },
        ],
      },
      {
        id: 'trying-it-on',
        capability: 'ask-to-try-on',
        title: 'Ask to try it on',
        cue: 'One question, four shapes. Naming the item is what stops the pointing.',
        initiallyVisible: 3,
        responses: [
          { item: '000565', nuance: 'Folded into answering about your size' },
          { item: '001186', nuance: 'Asks for the fitting room without naming it' },
          { item: '001188', nuance: 'Names the item you are holding' },
          { item: '001187', nuance: 'For when you cannot choose yet' },
          { item: '000607', nuance: 'The masculine form of the same question' },
          { item: '001189', nuance: 'A statement, after the first one did not fit' },
          { item: '000657', nuance: 'Plural, for shoes or trousers' },
          { item: '000664', nuance: 'Quiero rather than puedo — a shade more direct' },
        ],
      },
      {
        id: 'taking-it',
        capability: 'choose-clothing-purchase',
        title: 'Decide, out loud',
        cue: '“Me lo llevo” is the sentence that ends the exchange. Leaving is also an answer.',
        initiallyVisible: 3,
        responses: [
          { item: '001190', nuance: 'The plain decision' },
          { item: '000567', nuance: 'Decides and asks the price in one line' },
          { item: '001191', nuance: 'Chooses between two' },
          { item: '000609', nuance: 'Says you like it, then takes it' },
          { item: '000659', nuance: 'Plural, and says why' },
          { item: '001192', nuance: 'A polite no that leaves the door open' },
          { item: '000666', nuance: 'Gives the reason instead of the verdict' },
          { item: '000668', nuance: 'Short, after you have already decided' },
        ],
      },
      {
        id: 'what-it-costs',
        capability: 'ask-understand-item-price',
        title: 'Ask the price',
        cue: 'Ask before the fitting room, not after. It changes what you try on.',
        initiallyVisible: 3,
        responses: [
          { item: '001193', nuance: 'Before you commit to trying it on' },
          { item: '000567', nuance: 'Folded into taking it' },
          { item: '001194', nuance: 'For two items at once' },
          { item: '000609', nuance: 'After you have decided you like it' },
          { item: '001195', nuance: 'When you missed the price the first time' },
          { item: '000659', nuance: 'Plural, for shoes or trousers' },
          { item: '001196', nuance: 'Worth asking before you get to the till' },
          { item: '000666', nuance: 'Asks the price of the pair' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 11,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the shop assistant',
  },
  {
    id: 'hotel-check-in',
    language: 'es',
    level: 'a1',
    order: 5,
    title: 'Check into a hotel',
    goal: 'Confirm a reservation and understand the essential check-in details.',
    passage: '700012',
    transfers: [
      {
        passage: '700018',
        support: 'guided',
        brief: 'Check in for a different stay and locate another hotel facility.',
      },
      {
        passage: '700027',
        support: 'guided',
        brief: 'Confirm a single room, breakfast times and where to find reception services.',
      },
      {
        passage: '700028',
        support: 'independent',
        brief: 'Complete a late check-in from intention cues and ask for essential details.',
      },
    ],
    capabilities: [
      'confirm-hotel-reservation',
      'give-stay-details',
      'ask-whats-included',
      'understand-hotel-schedule',
      'locate-hotel-facility',
    ],
    responsePalettes: [
      {
        id: 'hotel-stay-details',
        capability: 'give-stay-details',
        title: 'Give the details the receptionist needs',
        cue: 'Confirm the booking and add the detail that matters: room, nights, name, guests or breakfast.',
        initiallyVisible: 3,
        responses: [
          { item: '000763', nuance: 'The simplest confirmation' },
          { item: '000764', nuance: 'Give room type and duration together' },
          { item: '000765', nuance: 'Describe the stay without starting with sí' },
          { item: '000766', nuance: 'Give the reservation name' },
          { item: '000767', nuance: 'Answer only the duration question' },
          { item: '000768', nuance: 'Clarify the number of guests' },
          { item: '000769', nuance: 'Clarify an included option' },
          { item: '000770', nuance: 'Handle arriving without a booking' },
        ],
      },
      {
        id: 'arriving',
        capability: 'confirm-hotel-reservation',
        title: 'Say why you are standing there',
        cue: 'The receptionist asks one question. Answer it with the detail they need next.',
        initiallyVisible: 3,
        responses: [
          { item: '001197', nuance: 'Opens the whole exchange in one line' },
          { item: '000575', nuance: 'Room type and length of stay at once' },
          { item: '001198', nuance: 'The detail they actually need' },
          { item: '000612', nuance: 'Just the nights, when the room is already fixed' },
          { item: '001199', nuance: 'Adds how long, unprompted' },
          { item: '000670', nuance: 'A single room, spelled out' },
          { item: '000677', nuance: 'One night, under a name' },
          { item: '001200', nuance: 'The other case, and it happens' },
        ],
      },
      {
        id: 'whats-included',
        capability: 'ask-whats-included',
        title: 'Ask what comes with it',
        cue: 'Breakfast is the usual one. Asking openly gets you things you would not have asked for.',
        initiallyVisible: 3,
        responses: [
          { item: '000576', nuance: 'Names the price explicitly' },
          { item: '000327', nuance: 'The same question with the verb first' },
          { item: '000613', nuance: 'The short everyday version' },
          { item: '001201', nuance: 'Open, so you hear about more than breakfast' },
          { item: '000672', nuance: 'Skips included and goes straight to when' },
          { item: '001202', nuance: 'The question behind the question' },
          { item: '001203', nuance: 'Cheap rooms sometimes do not have one' },
          { item: '000679', nuance: 'Both halves in one question' },
        ],
      },
      {
        id: 'hotel-times',
        capability: 'understand-hotel-schedule',
        title: 'Get the times straight',
        cue: 'When it finishes matters more than when it starts. Ask for both.',
        initiallyVisible: 3,
        responses: [
          { item: '001204', nuance: 'The one you will need tomorrow morning' },
          { item: '001205', nuance: 'More useful than when it starts' },
          { item: '000672', nuance: 'The open version' },
          { item: '001206', nuance: 'Check-out, without needing the word for it' },
          { item: '001207', nuance: 'Proposes a time and lets them correct it' },
          { item: '001208', nuance: 'For the evening' },
          { item: '001209', nuance: 'When your train gets in at midnight' },
          { item: '000679', nuance: 'Included and when, in one' },
        ],
      },
      {
        id: 'hotel-facilities',
        capability: 'locate-hotel-facility',
        title: 'Find your way around it',
        cue: 'Ask at the desk while you are there. Nobody wants to come back down for it.',
        initiallyVisible: 3,
        responses: [
          { item: '000311', nuance: 'The most-asked question in any building' },
          { item: '001211', nuance: 'Ask before you carry the bags up' },
          { item: '000578', nuance: 'Whether there is one, before where' },
          { item: '001210', nuance: 'Outside the hotel rather than in it' },
          { item: '000615', nuance: 'For the evening' },
          { item: '000674', nuance: 'Where, once you know it exists' },
          { item: '001212', nuance: 'For a hotel with more than one door' },
          { item: '000681', nuance: 'The one that saves four flights of stairs' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 10,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the receptionist',
  },
  {
    id: 'make-plans',
    language: 'es',
    level: 'a1',
    order: 6,
    title: 'Make evening plans',
    goal: 'Suggest an activity, respond and agree on what to do.',
    passage: '700014',
    transfers: [
      {
        passage: '700019',
        support: 'guided',
        brief: 'Make a different plan for the afternoon.',
      },
      {
        passage: '700029',
        support: 'guided',
        brief: 'Suggest dinner, respond to an alternative and agree on a time.',
      },
      {
        passage: '700030',
        support: 'independent',
        brief: 'Arrange a weekend activity from intention cues and settle the details.',
      },
    ],
    capabilities: [
      'open-social-planning',
      'suggest-social-activity',
      'respond-to-suggestion',
      'coordinate-plan-time',
      'confirm-social-plan',
    ],
    responsePalettes: [
      {
        id: 'plan-reaction',
        capability: 'respond-to-suggestion',
        title: 'Accept, adjust, counter or decline',
        cue: 'Respond honestly to the suggestion. You can accept it, change one detail, offer another idea or decline politely.',
        initiallyVisible: 3,
        responses: [
          { item: '000771', nuance: 'Simple positive acceptance' },
          { item: '000772', nuance: 'Warm and enthusiastic acceptance' },
          { item: '000773', nuance: 'Casual and decisive' },
          { item: '000774', nuance: 'Accept while changing the time' },
          { item: '000775', nuance: 'Offer a preferred alternative' },
          { item: '000776', nuance: 'Give a clear practical refusal' },
          { item: '000777', nuance: 'Decline politely with a reason' },
          { item: '000778', nuance: 'Keep the relationship open' },
          { item: '000779', nuance: 'Use a softer personal refusal' },
          { item: '000780', nuance: 'Respond with a different suggestion' },
        ],
      },
      {
        id: 'opening-plans',
        capability: 'open-social-planning',
        title: 'Open the subject',
        cue: 'Ask before you suggest. It gives them somewhere to go that is not a no.',
        initiallyVisible: 3,
        responses: [
          { item: '000587', nuance: 'For tonight, with nothing assumed' },
          { item: '001213', nuance: 'Opens without committing you to anything' },
          { item: '000683', nuance: 'Checks for plans before offering one' },
          { item: '001215', nuance: 'Checks first, suggests after' },
          { item: '000617', nuance: 'The same for an afternoon' },
          { item: '001214', nuance: 'Direct, and easy to say yes to' },
          { item: '000689', nuance: 'Asks what they want rather than what you do' },
          { item: '001216', nuance: 'Assumes the plan and asks only what' },
        ],
      },
      {
        id: 'suggesting',
        capability: 'suggest-social-activity',
        title: 'Put something on the table',
        cue: 'A suggestion with a time or a place attached is far easier to answer.',
        initiallyVisible: 3,
        responses: [
          { item: '000588', nuance: 'Admits you have no idea, then offers one' },
          { item: '001217', nuance: 'The lowest-commitment suggestion there is' },
          { item: '000618', nuance: 'Short, and outdoors' },
          { item: '001219', nuance: 'Names somewhere specific' },
          { item: '000684', nuance: 'Turns down theirs and offers yours' },
          { item: '001218', nuance: 'A suggestion with a time attached' },
          { item: '000690', nuance: 'Podemos, which is softer than quieres' },
          { item: '001220', nuance: 'Apetecer is the natural verb for this in Spain' },
        ],
      },
      {
        id: 'settling-the-time',
        capability: 'coordinate-plan-time',
        title: 'Settle when and where',
        cue: 'A plan without a time is not a plan. Propose one rather than asking for one.',
        initiallyVisible: 3,
        responses: [
          { item: '001221', nuance: 'The plain question' },
          { item: '000590', nuance: 'Anchors the time to the event' },
          { item: '001222', nuance: 'Proposes a time rather than asking for one' },
          { item: '000620', nuance: 'About meeting rather than about the event' },
          { item: '001223', nuance: 'Moves the time without rejecting the plan' },
          { item: '000686', nuance: 'Adds something before the main plan' },
          { item: '001224', nuance: 'The other half of the arrangement' },
          { item: '000692', nuance: 'Proposes a time around a fixed one' },
        ],
      },
      {
        id: 'confirming-the-plan',
        capability: 'confirm-social-plan',
        title: 'Say it back',
        cue: 'Repeat the time, the place or the day. That is what turns talk into a plan.',
        initiallyVisible: 3,
        responses: [
          { item: '000592', nuance: 'Says the time back' },
          { item: '001225', nuance: 'Says the day back, which is what fixes it' },
          { item: '000622', nuance: 'Says the place back' },
          { item: '001226', nuance: 'Agrees and repeats the hour' },
          { item: '000688', nuance: 'Place and time together' },
          { item: '001227', nuance: 'Casual, and very Spanish' },
          { item: '000694', nuance: 'Day and place, for a plan further off' },
          { item: '001228', nuance: 'Warm, for a plan you are pleased about' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 10,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'a friend',
  },
  {
    id: 'morning-routine',
    language: 'es',
    level: 'a1',
    order: 7,
    title: 'Describe your morning',
    goal: 'Tell someone the main events in your morning in a connected sequence.',
    passage: '700001',
    transfers: [
      {
        passage: '700020',
        support: 'guided',
        brief: 'Describe a slower Saturday morning with a different destination.',
      },
      {
        passage: '700031',
        support: 'guided',
        brief: 'Describe a busy weekday morning with clear sequence and times.',
      },
      {
        passage: '700032',
        support: 'independent',
        brief: 'Build a connected Sunday routine from intention cues.',
      },
    ],
    capabilities: [
      'anchor-routine-in-time',
      'describe-routine-actions',
      'add-context-to-routine',
      'sequence-routine-events',
      'connect-routine-to-destination',
    ],
    responsePalettes: [
      {
        id: 'real-morning-action',
        capability: 'describe-routine-actions',
        title: 'Make the routine yours',
        cue: 'Say something true about your morning. Add a time, sequence word, place or destination when you can.',
        initiallyVisible: 3,
        responses: [
          { item: '000781', nuance: 'Anchor a habit with frequency and time' },
          { item: '000782', nuance: 'Begin a sequence clearly' },
          { item: '000783', nuance: 'Add the next action' },
          { item: '000784', nuance: 'Personalise breakfast' },
          { item: '000785', nuance: 'Add another habitual activity' },
          { item: '000786', nuance: 'Combine an action with a place' },
          { item: '000787', nuance: 'Connect an action to a time' },
          { item: '000788', nuance: 'Add destination and transport' },
          { item: '000789', nuance: 'Contrast a weekend habit' },
          { item: '000790', nuance: 'Connect events with antes de' },
        ],
      },
      {
        id: 'anchoring-in-time',
        capability: 'anchor-routine-in-time',
        title: 'Put it on the clock',
        cue: 'A routine without a time is a list. The hour is what makes it yours.',
        initiallyVisible: 3,
        responses: [
          { item: '000516', nuance: 'Waking, with the hour' },
          { item: '000695', nuance: 'A weekday, and a half hour' },
          { item: '000623', nuance: 'A day of the week rather than a time' },
          { item: '000700', nuance: 'A late start, said plainly' },
          { item: '000520', nuance: 'Arriving rather than leaving' },
          { item: '000698', nuance: 'The hour, and the reason for it' },
          { item: '000626', nuance: 'Mid-morning, and where you go' },
          { item: '000704', nuance: 'Midday, with who you go with' },
        ],
      },
      {
        id: 'routine-context',
        capability: 'add-context-to-routine',
        title: 'Add the circumstance',
        cue: 'The weather, the reason, the room. One clause is what turns a list into a morning.',
        initiallyVisible: 3,
        responses: [
          { item: '000517', nuance: 'The weather, and how you feel about it' },
          { item: '001237', nuance: 'A circumstance rather than an action' },
          { item: '000697', nuance: 'Adds the room to the action' },
          { item: '000701', nuance: 'Two small actions in order' },
          { item: '000702', nuance: 'What you eat and read, together' },
          { item: '000698', nuance: 'Porque, giving the reason' },
          { item: '000627', nuance: 'Allí, pointing back at the place' },
          { item: '000623', nuance: 'The day, as the frame for everything after' },
        ],
      },
      {
        id: 'sequencing',
        capability: 'sequence-routine-events',
        title: 'Put it in order',
        cue: 'Primero, después, luego. Three words that hold a whole morning together.',
        initiallyVisible: 3,
        responses: [
          { item: '000516', nuance: 'The first event' },
          { item: '000624', nuance: 'Primero, opening the sequence' },
          { item: '000696', nuance: 'Two actions in one step' },
          { item: '000518', nuance: 'Eating and drinking as one moment' },
          { item: '000697', nuance: 'Después, moving it on' },
          { item: '000625', nuance: 'Después, with two chores' },
          { item: '000703', nuance: 'Después, later in the morning' },
          { item: '000519', nuance: 'Leaving, and how you travel' },
        ],
      },
      {
        id: 'where-it-leads',
        capability: 'connect-routine-to-destination',
        title: 'Say where it ends up',
        cue: 'A morning goes somewhere. Name the place, how you get there and when you arrive.',
        initiallyVisible: 3,
        responses: [
          { item: '000519', nuance: 'Leaving and travelling, in one line' },
          { item: '001238', nuance: 'How you travel, and when you land' },
          { item: '000520', nuance: 'Arriving, with the hour' },
          { item: '000699', nuance: 'Both halves: the transport and the arrival' },
          { item: '001239', nuance: 'A different destination, the same shape' },
          { item: '000626', nuance: 'Somewhere that is not work' },
          { item: '000627', nuance: 'What you do once you are there' },
          { item: '000704', nuance: 'Who you go with' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 9,
    scenarioPartner: 'a new friend',
  },
  /**
   * The first A2 mission, and the first built on material that was already in
   * the pack: `En el médico` was the one dialogue no mission claimed.
   *
   * Health is the survival scenario the seven A1 missions leave out — a learner
   * can order a coffee and check into a hotel but cannot say what hurts. It sits
   * at A2 because its taught exchange does: `¿Desde cuándo?` wants a past
   * reference, which is exactly why it earns a level of its own rather than
   * being forced into A1.
   *
   * The transfer ladder deliberately leaves the surgery. Naming the symptom to a
   * pharmacist and to a receptionist on the phone is the same ability under
   * different pressure, which is what transfer is for — a second appointment
   * with a different doctor would mostly re-run the script.
   */
  {
    id: 'doctor-visit',
    language: 'es',
    level: 'a2',
    order: 8,
    title: 'Say what hurts',
    goal: 'Describe a symptom, say how long you have had it, and follow the advice you are given.',
    passage: '700013',
    transfers: [
      {
        passage: '700037',
        support: 'guided',
        brief: 'Ask a pharmacist for something for a headache, and take the dosage in.',
      },
      {
        passage: '700038',
        support: 'guided',
        brief: 'A different symptom and a different doctor: your back, and how many days.',
      },
      {
        passage: '700039',
        support: 'independent',
        brief: 'Phone a health centre for an appointment from intention cues alone.',
      },
    ],
    capabilities: [
      'describe-a-symptom',
      'say-since-when',
      'answer-health-questions',
      'follow-health-advice',
    ],
    responsePalettes: [
      {
        /*
         * Every option here is a sentence the pack already had — the symptoms
         * were authored long before this mission existed, scattered across the
         * body and health sheets. Pointing at them rather than writing ten near
         * copies is the same rule content follows everywhere else: describe what
         * exists, do not duplicate it. The build would have rejected the copies
         * anyway, since no two items may carry the same text.
         */
        id: 'symptom-report',
        capability: 'describe-a-symptom',
        title: 'Say what is actually wrong',
        cue: 'Name what hurts, or how you feel. Add where and how much when you can.',
        initiallyVisible: 3,
        responses: [
          { item: '000365', nuance: 'The most common complaint of all' },
          { item: '000366', nuance: 'A different part of the body' },
          { item: '000367', nuance: 'A symptom with tener rather than doler' },
          { item: '000145', nuance: 'Two places at once' },
          { item: '000148', nuance: 'Naming which side' },
          { item: '000150', nuance: 'Plural: doler agrees with what hurts' },
          { item: '000046', nuance: 'Not pain but a state · masculine speaker' },
          { item: '000047', nuance: 'The same state, stronger and today' },
          { item: '000368', nuance: 'Includes how long it has been' },
          { item: '000155', nuance: 'Asking for a remedy rather than reporting' },
        ],
      },
      {
        id: 'since-when',
        capability: 'say-since-when',
        title: 'Say how long',
        cue: 'The second question is always “¿desde cuándo?”. Have a shape ready for the answer.',
        initiallyVisible: 3,
        responses: [
          { item: '000368', nuance: 'Desde plus a day' },
          { item: '001240', nuance: 'Desde hace plus a count of days' },
          { item: '000583', nuance: 'A day, and what it stopped you doing' },
          { item: '001241', nuance: 'Anchors it to a day rather than a count' },
          { item: '000796', nuance: 'This morning, with the moment it began' },
          { item: '001242', nuance: 'Says when it began instead of how long' },
          { item: '000804', nuance: 'Approximate, and honest about it' },
          { item: '000814', nuance: 'A stretch of time rather than a point' },
        ],
      },
      {
        id: 'answering-the-doctor',
        capability: 'answer-health-questions',
        title: 'Answer the follow-ups',
        cue: 'Fever, medication, sleep, appetite. The same four questions, in every surgery.',
        initiallyVisible: 3,
        responses: [
          { item: '000585', nuance: 'No, with the symptom you do have' },
          { item: '001243', nuance: 'Yes, with the degree' },
          { item: '000798', nuance: 'None, and what you do have' },
          { item: '001244', nuance: 'The question they always ask' },
          { item: '000806', nuance: 'About sleep, with the reason' },
          { item: '001245', nuance: 'About sleep, with a start date' },
          { item: '001246', nuance: 'Rules one thing out and offers another' },
          { item: '000816', nuance: 'Accepting an appointment time' },
        ],
      },
      {
        id: 'taking-the-advice',
        capability: 'follow-health-advice',
        title: 'Take the advice',
        cue: 'Repeat what you have been told to do. It is how you find out you misheard it.',
        initiallyVisible: 3,
        responses: [
          { item: '000792', nuance: 'Thanks, and the one thing you will do' },
          { item: '001247', nuance: 'Accepts, and says how much' },
          { item: '001248', nuance: 'Repeats the instruction back' },
          { item: '000800', nuance: 'Formal thanks for the help' },
          { item: '001249', nuance: 'Accepts, then asks the obvious next question' },
          { item: '000808', nuance: 'Short, and commits to it' },
          { item: '001250', nuance: 'Names the advice you will follow' },
          { item: '000818', nuance: 'Confirms you will bring what was asked' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 8,
    learnerSpeaker: 'Paciente',
    scenarioPartner: 'the doctor',
  },
  /**
   * Built on `Un día en la oficina`, which had sat in the pack unclaimed.
   *
   * A monologue mission rather than a dialogue, like `morning-routine`: "what do
   * you do?" is answered in a paragraph, not an exchange, and the transfer is a
   * different *job* rather than a different interlocutor. The last rung moves
   * into the past tense on purpose — recounting a specific bad day is the point
   * at which describing work stops being a script.
   */
  {
    id: 'your-work',
    language: 'es',
    level: 'a1',
    order: 9,
    title: 'Talk about your work',
    goal: 'Say what you do, take someone through a working day, and say how it left you.',
    passage: '700003',
    transfers: [
      {
        passage: '700040',
        support: 'guided',
        brief: 'The same day from home: a different place, the same shape.',
      },
      {
        passage: '700041',
        support: 'guided',
        brief: 'A different job entirely — a shop, with opening and closing times.',
      },
      {
        passage: '700042',
        support: 'independent',
        brief: 'Recount one particular busy day, in the past, from intention cues.',
      },
    ],
    capabilities: [
      'say-what-you-do',
      'walk-through-a-workday',
      'talk-about-work-meetings',
      'say-how-the-day-went',
    ],
    responsePalettes: [
      {
        id: 'what-you-do',
        capability: 'say-what-you-do',
        title: 'Say what you actually do',
        cue: 'Name the job, or the place, or who you do it with — whatever is true.',
        initiallyVisible: 3,
        responses: [
          { item: '000849', nuance: 'The job before the place' },
          { item: '000850', nuance: 'Adds who you work with' },
          { item: '000851', nuance: 'For someone studying as well' },
          { item: '000852', nuance: 'Where rather than what' },
          { item: '000853', nuance: 'Honest, when you are between jobs' },
          { item: '000854', nuance: 'Adds how near it is' },
          { item: '000855', nuance: 'Says more than the question asked' },
          { item: '000856', nuance: 'A precise job · feminine speaker' },
        ],
      },
      {
        id: 'the-working-day',
        capability: 'walk-through-a-workday',
        title: 'Take them through it',
        cue: 'Start, middle, end. Each step is one clause with an hour in it.',
        initiallyVisible: 3,
        responses: [
          { item: '000527', nuance: 'Arriving, and the first task' },
          { item: '000820', nuance: 'An earlier start, compared to somewhere else' },
          { item: '000825', nuance: 'Opening up, and who you deal with' },
          { item: '000529', nuance: 'Lunch, with who and when' },
          { item: '000822', nuance: 'The break, and how long it is' },
          { item: '000827', nuance: 'The quiet half of the day' },
          { item: '000530', nuance: 'Finishing, and how it left you' },
          { item: '000830', nuance: 'In the past, with what was waiting' },
        ],
      },
      {
        id: 'meetings',
        capability: 'talk-about-work-meetings',
        title: 'Who you meet, and when',
        cue: 'Name the person, or the hour, or how often. Any of the three is an answer.',
        initiallyVisible: 3,
        responses: [
          { item: '000528', nuance: 'Who with, and the hour' },
          { item: '001251', nuance: 'How many, over what period' },
          { item: '000821', nuance: 'By phone rather than in a room' },
          { item: '001252', nuance: 'For work that is meetings by another name' },
          { item: '000826', nuance: 'A colleague coming to you' },
          { item: '001253', nuance: 'A regular one, anchored to a day' },
          { item: '000831', nuance: 'Two of them, in the past' },
          { item: '000529', nuance: 'The meeting that is really lunch' },
        ],
      },
      {
        id: 'how-it-went',
        capability: 'say-how-the-day-went',
        title: 'Say how it left you',
        cue: 'Tired is not the same as bad. Give the verdict and the reason together.',
        initiallyVisible: 3,
        responses: [
          { item: '000530', nuance: 'Finishing time, and the state it left you in' },
          { item: '001254', nuance: 'Two verdicts at once, which is usually the truth' },
          { item: '000823', nuance: 'Early, and what that buys you' },
          { item: '001255', nuance: 'The reason and the feeling together' },
          { item: '000828', nuance: 'Closing up, and going home content' },
          { item: '001256', nuance: 'Tired, but not unhappy' },
          { item: '000829', nuance: 'The whole day summed up in one word' },
          { item: '000833', nuance: 'In the past, with the hour' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 9,
    scenarioPartner: 'someone you have just met',
  },
  /**
   * Built on `Mi piso`, the other text nothing pointed at.
   *
   * The transfers deliberately change *who is speaking about what home* rather
   * than only the rooms: your parents' house, a student room, a flat two people
   * are still looking for. The last one is in the future rather than the present,
   * which is where "describe your home" stops being a list of furniture.
   */
  {
    id: 'your-home',
    language: 'es',
    level: 'a1',
    order: 10,
    title: 'Describe where you live',
    goal: 'Say where you live, what the rooms are like, what is nearby, and how you feel about it.',
    passage: '700002',
    transfers: [
      {
        passage: '700043',
        support: 'guided',
        brief: "Someone else's home: a village house, with a garden and a river.",
      },
      {
        passage: '700044',
        support: 'guided',
        brief: 'A much smaller home, and what it is missing.',
      },
      {
        passage: '700045',
        support: 'independent',
        brief: 'A home you do not have yet — say what you are looking for.',
      },
    ],
    capabilities: [
      'say-where-you-live',
      'describe-the-rooms',
      'say-what-is-nearby',
      'say-how-you-feel-about-home',
    ],
    responsePalettes: [
      {
        id: 'where-you-live',
        capability: 'say-where-you-live',
        title: 'Say where you really live',
        cue: 'Say the kind of home, the area, or who you live with. Any of the three is an answer.',
        initiallyVisible: 3,
        responses: [
          { item: '000857', nuance: 'Area and kind of home' },
          { item: '000858', nuance: 'Who you live with' },
          { item: '000859', nuance: 'Away from the centre' },
          { item: '000860', nuance: 'Alone · masculine speaker' },
          { item: '000861', nuance: 'A landmark instead of a street' },
          { item: '000862', nuance: 'Separates where you live from where you are from' },
          { item: '000863', nuance: 'A detail that says how it feels' },
          { item: '000864', nuance: 'How long, with desde hace' },
        ],
      },
      {
        id: 'the-rooms',
        capability: 'describe-the-rooms',
        title: 'Describe the rooms',
        cue: 'How many, how big, what is in them, and what state they are in.',
        initiallyVisible: 3,
        responses: [
          { item: '000835', nuance: 'How many rooms, in one line' },
          { item: '000522', nuance: 'One room, with a detail' },
          { item: '000836', nuance: 'What is in it, and what it is made of' },
          { item: '000523', nuance: 'The state it is in' },
          { item: '000840', nuance: 'What you own rather than what the room is' },
          { item: '000841', nuance: 'Shared, and honest about it' },
          { item: '000845', nuance: 'What you want rather than what you have' },
          { item: '000846', nuance: 'Two rooms and two requirements' },
        ],
      },
      {
        id: 'whats-nearby',
        capability: 'say-what-is-nearby',
        title: 'What is around it',
        cue: 'Hay is the whole trick. What is missing counts as much as what is there.',
        initiallyVisible: 3,
        responses: [
          { item: '000524', nuance: 'What is missing, then what is there' },
          { item: '001257', nuance: 'The thing people ask about first' },
          { item: '000837', nuance: 'Two things, one behind and one near' },
          { item: '001258', nuance: 'Names how close, not just that it exists' },
          { item: '000842', nuance: 'The same street, which is closer than cerca' },
          { item: '001259', nuance: 'What is missing, and why it matters' },
          { item: '000847', nuance: 'What you need nearby, not what is' },
          { item: '001260', nuance: 'Puts the place first, which is natural in Spanish' },
        ],
      },
      {
        id: 'how-it-feels',
        capability: 'say-how-you-feel-about-home',
        title: 'How you feel about it',
        cue: 'Yes, no, or yes-but. The “but” is where the real answer usually is.',
        initiallyVisible: 3,
        responses: [
          { item: '000525', nuance: 'A plain yes' },
          { item: '001261', nuance: 'About the living, not the flat' },
          { item: '000843', nuance: 'Small, but happy — the commonest answer there is' },
          { item: '001262', nuance: 'The honest verdict most people give' },
          { item: '000838', nuance: 'Fine to visit, not to live in' },
          { item: '001263', nuance: 'Negative, and says exactly what about' },
          { item: '000848', nuance: 'Hard, but hopeful' },
          { item: '001264', nuance: 'A feeling expressed as a plan' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 8,
    scenarioPartner: 'a new neighbour',
  },
  /**
   * The largest gap in the seven A1 missions relative to what the pack already
   * knew: travel was its biggest topic and its only travel dialogues were asking
   * directions and checking into a hotel. A learner could find the station and
   * sleep near it without ever buying a ticket.
   *
   * The ladder changes the *mode* rather than the destination — bus, return fare,
   * metro — because the pressure in this exchange comes from the fare and the
   * platform, not from where you are going.
   */
  {
    id: 'buy-a-ticket',
    language: 'es',
    level: 'a1',
    order: 11,
    title: 'Buy a ticket',
    goal: 'Ask for a ticket, choose the fare, and find out when and where it leaves.',
    passage: '700046',
    transfers: [
      {
        passage: '700047',
        support: 'guided',
        brief: 'A bus rather than a train, and a stop rather than a platform.',
      },
      {
        passage: '700048',
        support: 'guided',
        brief: 'A return for two people, with a choice between two departures.',
      },
      {
        passage: '700049',
        support: 'independent',
        brief: 'A metro machine: single or ten journeys, from intention cues.',
      },
    ],
    capabilities: ['ask-for-a-ticket', 'ask-about-departure', 'choose-a-fare', 'find-the-platform'],
    responsePalettes: [
      {
        id: 'ticket-request',
        capability: 'ask-for-a-ticket',
        title: 'Ask for the ticket you need',
        cue: 'Say where you are going, or how many, or which fare — any of the three opens it.',
        initiallyVisible: 3,
        responses: [
          { item: '000961', nuance: 'Destination first, short and direct' },
          { item: '000962', nuance: 'Says how many at the same time' },
          { item: '000963', nuance: 'Names the fare instead of the place' },
          { item: '000964', nuance: 'Whatever leaves soonest' },
          { item: '000965', nuance: 'Puts the price question first' },
          { item: '000966', nuance: 'Says which day it is for' },
          { item: '000967', nuance: 'For a group, without the word billete' },
          { item: '000968', nuance: 'When you already have one and are unsure' },
        ],
      },
      {
        id: 'when-it-leaves',
        capability: 'ask-about-departure',
        title: 'When it leaves, and when it lands',
        cue: 'The departure is half of it. What you actually need is the arrival.',
        initiallyVisible: 3,
        responses: [
          { item: '001265', nuance: 'The question that starts every journey' },
          { item: '000870', nuance: 'About the arrival, once you have the departure' },
          { item: '001266', nuance: 'Cuándo, when you do not need the exact hour' },
          { item: '000886', nuance: 'Choosing between two you have been offered' },
          { item: '001267', nuance: 'When the next one is too soon' },
          { item: '000878', nuance: 'About how busy it will be' },
          { item: '001268', nuance: 'About the arrival, which is what you need' },
          { item: '000894', nuance: 'About the last one of the day' },
        ],
      },
      {
        id: 'which-fare',
        capability: 'choose-a-fare',
        title: 'Choose the fare',
        cue: 'Single or return, how many, and for when. Answer two at once and save a turn.',
        initiallyVisible: 3,
        responses: [
          { item: '001269', nuance: 'The two words that answer the standard question' },
          { item: '000868', nuance: 'Single, then the price' },
          { item: '001270', nuance: 'How many and which fare at once' },
          { item: '000876', nuance: 'The day and the number together' },
          { item: '001271', nuance: 'Adds the day, which they will ask next' },
          { item: '000884', nuance: 'How many, with who' },
          { item: '001272', nuance: 'Asks the price before choosing' },
          { item: '000892', nuance: 'A multi-trip fare, with the reason' },
        ],
      },
      {
        id: 'which-platform',
        capability: 'find-the-platform',
        title: 'Find where it goes from',
        cue: 'Say the number back. A platform misheard is a train missed.',
        initiallyVisible: 3,
        responses: [
          { item: '001273', nuance: 'The last thing between you and the train' },
          { item: '000872', nuance: 'Says the number back, then thanks them' },
          { item: '001274', nuance: 'Once you know the number' },
          { item: '000888', nuance: 'Checks the number as a question' },
          { item: '001275', nuance: 'For a bus, where there is no platform' },
          { item: '000880', nuance: 'Reads back a direction rather than a number' },
          { item: '001276', nuance: 'Offers both, so the answer cannot be vague' },
          { item: '000896', nuance: 'A metro line rather than a platform' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 9,
    learnerSpeaker: 'Viajero',
    scenarioPartner: 'the person at the counter',
  },
  /**
   * `En el mercado` existed as a monologue and nothing let a learner *buy*
   * anything in it. Shopping already had four clothes dialogues, and a market is
   * usefully different: quantities and weights rather than sizes, and a price per
   * kilo rather than per item.
   *
   * The independent rung is the one that matters here — the stall is out of what
   * you asked for, so the script cannot be followed and something has to be
   * changed on the spot.
   */
  {
    id: 'market-shopping',
    language: 'es',
    level: 'a1',
    order: 12,
    title: 'Shop at the market',
    goal: 'Ask for an amount, find out what it costs by weight, change your order and pay.',
    passage: '700050',
    transfers: [
      {
        passage: '700051',
        support: 'guided',
        brief: 'A bakery: counted loaves rather than a weight, and a change of mind.',
      },
      {
        passage: '700052',
        support: 'guided',
        brief: 'A fishmonger, a higher price per kilo, and card or cash.',
      },
      {
        passage: '700053',
        support: 'independent',
        brief: 'They are out of what you wanted. Take the substitute and re-price it.',
      },
    ],
    capabilities: [
      'ask-for-a-quantity',
      'ask-price-by-weight',
      'change-what-you-asked-for',
      'pay-and-leave',
    ],
    responsePalettes: [
      {
        id: 'quantity-request',
        capability: 'ask-for-a-quantity',
        title: 'Ask for how much you want',
        cue: 'Weigh it, count it, or leave it vague — all three are what people actually say.',
        initiallyVisible: 3,
        responses: [
          { item: '000969', nuance: 'The everyday weight request' },
          { item: '000970', nuance: 'Half, with a limit made clear' },
          { item: '000971', nuance: 'Counted rather than weighed' },
          { item: '000972', nuance: 'Vague on purpose, and perfectly natural' },
          { item: '000973', nuance: 'Adds which size' },
          { item: '000974', nuance: 'The question form a stall expects' },
          { item: '000975', nuance: 'Small, with the courtesy at the end' },
          { item: '000976', nuance: 'For a stall you go back to' },
        ],
      },
      {
        id: 'by-weight',
        capability: 'ask-price-by-weight',
        title: 'Ask the price by weight',
        cue: '“¿A cuánto está?” is the market form. Learn it and you sound like a regular.',
        initiallyVisible: 3,
        responses: [
          { item: '000901', nuance: 'A cuánto están, plural, for produce' },
          { item: '001277', nuance: 'The straightforward form' },
          { item: '001278', nuance: 'A cuánto están is what you will actually hear' },
          { item: '000917', nuance: 'About the kilo rather than the item' },
          { item: '001279', nuance: 'For the amount you want, not the unit' },
          { item: '000909', nuance: 'Priced by the piece, not the kilo' },
          { item: '001280', nuance: 'Half a kilo is the usual market amount' },
          { item: '000925', nuance: 'Adds a second thing to the same question' },
        ],
      },
      {
        id: 'changing-your-order',
        capability: 'change-what-you-asked-for',
        title: 'Add, drop or change it',
        cue: '“Mejor” is how you change your mind politely. It carries no apology and needs none.',
        initiallyVisible: 3,
        responses: [
          { item: '000900', nuance: 'Adds a second thing, with the amount' },
          { item: '001281', nuance: 'Mejor is how you change an order politely' },
          { item: '000908', nuance: 'Declines, then changes its mind anyway' },
          { item: '001282', nuance: 'Says plainly that you are changing it' },
          { item: '000916', nuance: 'Declines more, and closes the order' },
          { item: '001283', nuance: 'Adds rather than changes' },
          { item: '000924', nuance: 'Takes what is there instead of what you wanted' },
          { item: '001284', nuance: 'Takes something back off the counter' },
        ],
      },
      {
        id: 'paying-and-going',
        capability: 'pay-and-leave',
        title: 'Pay and go',
        cue: 'Hand it over, say how you are paying, and leave a door open for next week.',
        initiallyVisible: 3,
        responses: [
          { item: '000904', nuance: 'Pays and names the next visit' },
          { item: '001285', nuance: 'Small stalls often prefer it' },
          { item: '000912', nuance: 'Tenga, which is what you say handing money over' },
          { item: '001286', nuance: 'Says the amount as you hand it over' },
          { item: '000920', nuance: 'Names the method, and wishes them the day' },
          { item: '001287', nuance: 'For a stall you will come back to' },
          { item: '000928', nuance: 'Says the amount back as you pay it' },
          { item: '001288', nuance: 'Confirms the change was right on the way out' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 9,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the stallholder',
  },
  /**
   * `greet-and-respond` gets a learner as far as hello and how are you. This is
   * the next thing anyone is asked, and the pack had thirty-seven family items
   * with no exchange to use them in.
   *
   * It reuses the characters of the greetings mission on purpose — Luis, Marta,
   * Ana, Daniel, Elena — so the two missions read as the same person's life
   * rather than as two unrelated scripts. The learner is Luis in both.
   */
  {
    id: 'introduce-your-family',
    language: 'es',
    level: 'a1',
    order: 13,
    title: 'Introduce your family',
    goal: 'Say who someone is, what they do, and give a detail — then react to what you hear.',
    passage: '700054',
    transfers: [
      {
        passage: '700055',
        support: 'guided',
        brief: 'A cousin at a party, and how often he visits.',
      },
      {
        passage: '700056',
        support: 'guided',
        brief: 'A sister with a different job, and her children.',
      },
      {
        passage: '700057',
        support: 'independent',
        brief: 'Your own household now: who you live with, and a baby’s age.',
      },
    ],
    capabilities: [
      'introduce-a-person',
      'say-what-they-do',
      'give-family-details',
      'react-with-interest',
    ],
    responsePalettes: [
      {
        id: 'who-they-are',
        capability: 'introduce-a-person',
        title: 'Say who someone is',
        cue: 'Give the relationship, the name, or where you know them from.',
        initiallyVisible: 3,
        responses: [
          { item: '000977', nuance: 'Relationship first, then the name' },
          { item: '000978', nuance: 'Says where you know them from' },
          { item: '000979', nuance: 'The set phrase for an introduction' },
          { item: '000980', nuance: 'Two people at once, plus a detail' },
          { item: '000981', nuance: 'A more formal name for an older person' },
          { item: '000982', nuance: 'Distinguishes one child from another' },
          { item: '000983', nuance: 'Says what you share rather than who they are' },
          { item: '000984', nuance: 'Anticipates that they will not know them' },
        ],
      },
      {
        id: 'what-they-do',
        capability: 'say-what-they-do',
        title: 'Say what they do',
        cue: 'The job, the place, or what they are studying. Whichever is easiest to say.',
        initiallyVisible: 3,
        responses: [
          { item: '000932', nuance: 'Job and place, in one line' },
          { item: '001289', nuance: 'Where, when the job has no short name' },
          { item: '000940', nuance: 'Studying and working at once' },
          { item: '001290', nuance: 'For someone doing both' },
          { item: '000948', nuance: 'Corrects the guess, then gives the job' },
          { item: '001291', nuance: 'Honest, and very common' },
          { item: '000956', nuance: 'A job, and what has changed about it' },
          { item: '001292', nuance: 'Job and place in one line' },
        ],
      },
      {
        id: 'family-details',
        capability: 'give-family-details',
        title: 'Give a detail',
        cue: 'Ages take tener, never ser. Numbers are what make a person real to a listener.',
        initiallyVisible: 3,
        responses: [
          { item: '000934', nuance: 'A sibling, with an age' },
          { item: '001293', nuance: 'The size of the household, in three words' },
          { item: '001294', nuance: 'Ages use tener, not ser' },
          { item: '000950', nuance: 'How many children, and which' },
          { item: '001295', nuance: 'Two ages without repeating años' },
          { item: '000942', nuance: 'How often, rather than how many' },
          { item: '001296', nuance: 'Where, rather than who or how old' },
          { item: '000958', nuance: 'Months, for a baby' },
        ],
      },
      {
        id: 'reacting',
        capability: 'react-with-interest',
        title: 'React, so they keep going',
        cue: 'A reaction is what turns an answer into a conversation. Two words is enough.',
        initiallyVisible: 3,
        responses: [
          { item: '000935', nuance: 'Warm, and says something about them' },
          { item: '000943', nuance: 'Interested, and asks to meet them' },
          { item: '000951', nuance: 'Glad, with an observation' },
          { item: '000959', nuance: 'Pleased for them, plainly' },
          { item: '000987', nuance: 'Interested, then a follow-up question' },
          { item: '000991', nuance: 'Reacts, then offers something of your own' },
          { item: '001003', nuance: 'Formal, and turns it into a question' },
          { item: '001013', nuance: 'Reacts and changes the subject in one line' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 9,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'a friend looking at your photos',
  },
  /*
   * ── B1 ────────────────────────────────────────────────────────────────
   *
   * The first missions above A2, and the reason the ladder stopped there was
   * never the engine: `missionsForCourse` has always taken a level ceiling, so
   * a B1 mission needed B1 *content* and there was none. `more-missions.md` §2.1
   * named this as the gap and said it was "not solved by writing more a1
   * missions" — thirteen of fourteen were a1, and a learner who finished them
   * had one a2 mission and then nothing.
   *
   * All three turn on the same grammar and are deliberately not *about* it. A B1
   * learner does not need a mission called "the subjunctive"; they need to
   * complain about a bill, settle something with a flatmate and take advice
   * without taking orders — and find, three passages in, that all of those need
   * `quiero que`, `es mejor que` and `dudo que` whether anybody named the mood
   * or not.
   *
   * The transfer ladder is steeper here than at A1. The last rung of each drops
   * more than the script: in `handle-a-complaint` it drops the counter, so there
   * is nobody paid to be patient with you; in `share-a-flat` the learner becomes
   * the one asking rather than the one asked.
   */
  {
    id: 'handle-a-complaint',
    language: 'es',
    level: 'b1',
    order: 14,
    title: 'Say something is wrong, and get it put right',
    goal: 'Explain what has gone wrong, say what you want done about it, and stay polite while holding the line.',
    passage: '700109',
    transfers: [
      {
        passage: '700115',
        support: 'guided',
        brief:
          'The same complaint down a phone line, about a bill that is twice what it should be.',
      },
      {
        passage: '700116',
        support: 'guided',
        brief:
          'A parcel that never came — and they offer a replacement when what you want is the money.',
      },
      {
        passage: '700117',
        support: 'independent',
        brief:
          'A neighbour rather than a shop: no counter to stand at, and nobody paid to be patient with you.',
      },
    ],
    capabilities: ['make-a-complaint', 'ask-someone-to-do', 'express-a-hope'],
    responsePalettes: [
      {
        id: 'complaint-opening',
        capability: 'make-a-complaint',
        title: 'Saying what is wrong',
        cue: 'Say what happened, or what it is doing to you. Blame is optional and usually unhelpful.',
        initiallyVisible: 3,
        responses: [
          { item: '001869', nuance: 'Flat and factual; hardest to argue with' },
          { item: '001873', nuance: 'States exactly what was done' },
          { item: '001933', nuance: 'Reports the symptom, not the fault' },
          { item: '001993', nuance: 'Names the effect on you instead of the cause' },
          { item: '002057', nuance: 'Says how it felt, which a fact alone does not' },
          { item: '002110', nuance: 'Appeals to fairness rather than to the rules' },
          { item: '002114', nuance: 'Understated, and about the thing rather than a person' },
          { item: '002074', nuance: 'Firm: a demand, not a report' },
        ],
      },
      {
        id: 'complaint-request',
        capability: 'ask-someone-to-do',
        title: 'Asking for what you want done',
        cue: 'A complaint without a request is a mood. Say what would settle it.',
        initiallyVisible: 3,
        responses: [
          { item: '001731', nuance: 'The plainest form of the ask' },
          { item: '001733', nuance: 'Direct, and with a deadline attached' },
          { item: '001734', nuance: 'Asking someone to stop rather than to start' },
          { item: '001735', nuance: 'Offered as a question, which is harder to refuse' },
          { item: '001736', nuance: 'A preference — softer than a request, still clear' },
          { item: '001740', nuance: 'Formal, to someone serving you' },
          { item: '001738', nuance: 'Puts the requirement on an institution, not a person' },
          { item: '001739', nuance: 'States a rule of your own instead of asking' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 12,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'someone on the other side of a counter',
  },
  {
    id: 'share-a-flat',
    language: 'es',
    level: 'b1',
    order: 15,
    title: 'Sort something out with the person you live with',
    goal: 'Raise something that is bothering you at home, propose a change, and reach an agreement neither of you resents.',
    passage: '700110',
    transfers: [
      {
        passage: '700118',
        support: 'guided',
        brief:
          'The same conversation about money, where the bills went up and neither of you caused it.',
      },
      {
        passage: '700119',
        support: 'guided',
        brief: 'Who cleans what — and the fix is a rota rather than a favour.',
      },
      {
        passage: '700120',
        support: 'independent',
        brief: 'You are the one asking this time, and the answer is not a foregone conclusion.',
      },
    ],
    capabilities: ['ask-someone-to-do', 'react-to-news', 'concede-a-point'],
    responsePalettes: [
      {
        id: 'flat-reaction',
        capability: 'react-to-news',
        title: 'Reacting without starting a row',
        cue: 'React to what they have just said before you answer it. The reaction is what keeps it a conversation.',
        initiallyVisible: 3,
        responses: [
          { item: '001777', nuance: 'Glad for them, plainly' },
          { item: '001778', nuance: 'Surprised, and mildly critical of everyone else' },
          { item: '001779', nuance: 'Annoyed, but at a situation rather than at them' },
          { item: '001780', nuance: 'Sorry about it, and says so first' },
          { item: '001781', nuance: 'Worried, and names the thing worrying you' },
          { item: '001783', nuance: 'Grateful they told you at all' },
          { item: '002117', nuance: 'Grants that their feeling makes sense' },
          { item: '002036', nuance: 'A light regret, for something nobody can help' },
        ],
      },
      {
        id: 'flat-request',
        capability: 'ask-someone-to-do',
        title: 'Proposing the change',
        cue: 'Ask for the change, not for an apology. A proposal is easier to agree to than a complaint.',
        initiallyVisible: 3,
        responses: [
          { item: '001736', nuance: 'A preference, which leaves them room' },
          { item: '001731', nuance: 'Direct, and assumes goodwill' },
          { item: '001734', nuance: 'Asking them to stop doing something' },
          { item: '001733', nuance: 'With a deadline, for when it has waited long enough' },
          { item: '001735', nuance: 'Offers to do it yourself instead' },
          { item: '001737', nuance: 'Reports what somebody else wants of you' },
          { item: '001739', nuance: 'States your own rule rather than asking for theirs' },
          { item: '001740', nuance: 'Formal — for a landlord rather than a flatmate' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 11,
    learnerSpeaker: 'Marta',
    scenarioPartner: 'the person you share a flat with',
  },
  {
    id: 'ask-for-advice',
    language: 'es',
    level: 'b1',
    order: 16,
    title: 'Ask for advice, weigh it, and decide',
    goal: 'Lay out a choice you cannot settle alone, take advice without taking orders, and say what you have decided.',
    passage: '700112',
    transfers: [
      {
        passage: '700121',
        support: 'guided',
        brief:
          'The same weighing-up about a course, where the cheaper option is not obviously the worse one.',
      },
      {
        passage: '700122',
        support: 'guided',
        brief: 'Money — and the first rung where you push back on the advice instead of taking it.',
      },
      {
        passage: '700123',
        support: 'independent',
        brief: 'A worry rather than a decision, and advice you would rather not have been given.',
      },
    ],
    // `weigh-two-options` is deliberately not here. It is what happens in the
    // model and the first two transfers, and it is not what happens in the
    // third — a worry about sleeping badly has no two options to weigh — so
    // declaring it would claim a transfer the last rung does not make.
    capabilities: ['give-advice', 'express-doubt'],
    responsePalettes: [
      {
        id: 'advice-giving',
        capability: 'give-advice',
        title: 'Advising without ordering',
        cue: 'Advice lands better as a suggestion than as an instruction. Say what you would do, or what is worth doing.',
        initiallyVisible: 3,
        responses: [
          { item: '002177', nuance: 'Softest: a suggestion, easily declined' },
          { item: '002167', nuance: 'Recommends a specific thing' },
          { item: '002168', nuance: 'Formal, to someone you do not know well' },
          { item: '002012', nuance: 'Flags it as advice, then says it bluntly' },
          { item: '002071', nuance: 'Gives the reason first and the instruction second' },
          { item: '001830', nuance: 'A warning, phrased in the negative' },
          { item: '002178', nuance: 'Points elsewhere rather than answering directly' },
          { item: '001931', nuance: 'Tells them what not to do, and why is left implied' },
        ],
      },
      {
        id: 'advice-doubt',
        capability: 'express-doubt',
        title: 'Not agreeing, without a row',
        cue: 'Say what you doubt rather than that they are wrong. Spanish moves the second verb for you.',
        initiallyVisible: 3,
        responses: [
          { item: '001767', nuance: 'Doubts the claim itself, mildly' },
          { item: '001768', nuance: 'Disagrees about degree, not about fact' },
          { item: '001969', nuance: 'Names the one thing that fails to persuade you' },
          { item: '001954', nuance: 'Hedged behind «me parece», so it stays an opinion' },
          { item: '002181', nuance: 'About likelihood rather than truth' },
          { item: '002160', nuance: 'Doubts that anything will change' },
          { item: '002001', nuance: 'Flat rejection; the strongest here' },
          { item: '001967', nuance: 'Rejects the argument rather than the conclusion' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 12,
    learnerSpeaker: 'Ana',
    scenarioPartner: 'a friend who has been through it',
  },
] as const;
