import type { MissionDefinition } from '../domain/missions';

/**
 * The first authored communicative journey.
 *
 * These are sequencing records over passages the pack already owns. Adding a
 * mission never creates a second copy of a sentence and never stores an
 * exercise. A future pack-supplied curriculum can implement the same shape.
 */
export const MISSIONS: readonly MissionDefinition[] = [
  {
    id: 'greet-and-respond',
    language: 'es',
    level: 'a1',
    order: 0,
    title: 'Greet and respond naturally',
    goal: 'Greet someone, ask how they are and choose an answer that fits how you feel.',
    passage: '700033',
    transfers: [
      {
        passage: '700034',
        support: 'guided',
        brief: 'Meet a friend and choose a natural answer about how you are doing.',
      },
      {
        passage: '700035',
        support: 'guided',
        brief: 'Use a more formal greeting at work and give an honest answer.',
      },
      {
        passage: '700036',
        support: 'independent',
        brief: 'Meet a new neighbour and respond from communicative intention cues.',
      },
    ],
    capabilities: [
      'greet-someone',
      'ask-about-wellbeing',
      'respond-to-wellbeing',
      'close-friendly-exchange',
    ],
    responsePalettes: [
      {
        id: 'wellbeing-answer',
        capability: 'respond-to-wellbeing',
        title: 'More than “I’m fine”',
        cue: 'Answer naturally according to how you feel. Add “¿Y tú?” or “¿Y usted?” when it fits.',
        initiallyVisible: 3,
        responses: [
          { item: '000709', nuance: 'Neutral and dependable' },
          { item: '000728', nuance: 'Enthusiastic and very positive' },
          { item: '000729', nuance: 'Casual and concise' },
          { item: '000730', nuance: 'Positive, but understated' },
          { item: '000731', nuance: 'So-so; neither good nor bad' },
          { item: '000732', nuance: 'Things could be better' },
          { item: '000791', nuance: 'A little tired · masculine speaker' },
          { item: '000733', nuance: 'Tired · feminine speaker' },
          { item: '000734', nuance: 'A gently softened sad answer' },
          { item: '000735', nuance: 'Clearly not doing well' },
        ],
      },
    ],
    spotlight: 4,
    estimatedMinutes: 11,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'the other person',
  },
  {
    id: 'cafe-order',
    language: 'es',
    level: 'a1',
    order: 1,
    title: 'Order at a café',
    goal: 'Order a drink, add something else and understand the price.',
    passage: '700009',
    transfers: [
      {
        passage: '700015',
        support: 'guided',
        brief: 'Order a different drink and respond when the waiter suggests an extra.',
      },
      {
        passage: '700021',
        support: 'guided',
        brief: 'Change the order, decline one option and ask for the new total.',
      },
      {
        passage: '700022',
        support: 'independent',
        brief: 'Handle a breakfast order from intention cues, without a line-by-line script.',
      },
    ],
    capabilities: [
      'order-food-drink',
      'handle-add-on',
      'ask-understand-price',
      'close-service-exchange',
    ],
    responsePalettes: [
      {
        id: 'cafe-order-choice',
        capability: 'order-food-drink',
        title: 'Build the order you actually want',
        cue: 'Order a drink naturally. Change the drink, milk, sugar or quantity to fit your choice.',
        initiallyVisible: 3,
        responses: [
          { item: '000739', nuance: 'Short, polite and direct' },
          { item: '000740', nuance: 'A dependable full request with quiero' },
          { item: '000741', nuance: 'Natural when ordering in a group' },
          { item: '000742', nuance: 'A common way to make your choice' },
          { item: '000743', nuance: 'A minimal everyday order' },
          { item: '000744', nuance: 'Remove an ingredient with sin' },
          { item: '000745', nuance: 'Add a preference with pero' },
          { item: '000746', nuance: 'Leave room to order more later' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 10,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the waiter',
  },
  {
    id: 'ask-directions',
    language: 'es',
    level: 'a1',
    order: 2,
    title: 'Ask for directions',
    goal: 'Ask where a place is and follow a short answer.',
    passage: '700011',
    transfers: [
      {
        passage: '700016',
        support: 'guided',
        brief: 'Find a different place and check how far away it is.',
      },
      {
        passage: '700023',
        support: 'guided',
        brief: 'Ask for the museum and follow a route with two landmarks.',
      },
      {
        passage: '700024',
        support: 'independent',
        brief: 'Find a bus stop from intention cues and confirm the distance.',
      },
    ],
    capabilities: [
      'ask-for-directions',
      'follow-simple-directions',
      'check-distance',
      'thank-for-help',
    ],
    responsePalettes: [
      {
        id: 'directions-destination',
        capability: 'ask-for-directions',
        title: 'More than one way to ask the way',
        cue: 'Ask for the place or route you need. Choose a direct, indirect or destination-first question.',
        initiallyVisible: 3,
        responses: [
          { item: '000747', nuance: 'Polite and direct' },
          { item: '000748', nuance: 'Slightly more formal with disculpe' },
          { item: '000749', nuance: 'Put the courtesy at the end' },
          { item: '000750', nuance: 'State what you are looking for' },
          { item: '000751', nuance: 'Soften the request with an indirect question' },
          { item: '000752', nuance: 'Ask for a route, not only a location' },
          { item: '000753', nuance: 'Check whether a known place is nearby' },
          { item: '000754', nuance: 'Explain the destination, then ask which way' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 9,
    learnerSpeaker: 'Turista',
    scenarioPartner: 'a local person',
  },
  {
    id: 'shop-clothes',
    language: 'es',
    level: 'a1',
    order: 3,
    title: 'Shop for clothes',
    goal: 'Ask for help, choose an item and handle the fitting-room exchange.',
    passage: '700010',
    transfers: [
      {
        passage: '700017',
        support: 'guided',
        brief: 'Choose a different item, size and colour.',
      },
      {
        passage: '700025',
        support: 'guided',
        brief: 'Ask for trousers, try them on and decide whether to buy them.',
      },
      {
        passage: '700026',
        support: 'independent',
        brief: 'Handle a shoe purchase from intention cues, including size and price.',
      },
    ],
    capabilities: [
      'seek-clothing-item',
      'handle-clothing-size',
      'ask-to-try-on',
      'choose-clothing-purchase',
      'ask-understand-item-price',
    ],
    responsePalettes: [
      {
        id: 'clothing-request',
        capability: 'seek-clothing-item',
        title: 'Shop by item, colour, fit or purpose',
        cue: 'Tell the assistant what you need—or politely say that you are only looking.',
        initiallyVisible: 3,
        responses: [
          { item: '000755', nuance: 'Name an item and colour' },
          { item: '000756', nuance: 'Use quiero for a direct choice' },
          { item: '000757', nuance: 'Use necesito when it is a need' },
          { item: '000758', nuance: 'Use estoy buscando for an ongoing search' },
          { item: '000759', nuance: 'Keep the item and change its colour' },
          { item: '000760', nuance: 'Ask for a different fit' },
          { item: '000761', nuance: 'Politely decline help' },
          { item: '000762', nuance: 'Describe quality and purpose instead of an item' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 11,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the shop assistant',
  },
  {
    id: 'hotel-check-in',
    language: 'es',
    level: 'a1',
    order: 4,
    title: 'Check into a hotel',
    goal: 'Confirm a reservation and understand the essential check-in details.',
    passage: '700012',
    transfers: [
      {
        passage: '700018',
        support: 'guided',
        brief: 'Check in for a different stay and locate another hotel facility.',
      },
      {
        passage: '700027',
        support: 'guided',
        brief: 'Confirm a single room, breakfast times and where to find reception services.',
      },
      {
        passage: '700028',
        support: 'independent',
        brief: 'Complete a late check-in from intention cues and ask for essential details.',
      },
    ],
    capabilities: [
      'confirm-hotel-reservation',
      'give-stay-details',
      'ask-whats-included',
      'understand-hotel-schedule',
      'locate-hotel-facility',
    ],
    responsePalettes: [
      {
        id: 'hotel-stay-details',
        capability: 'give-stay-details',
        title: 'Give the details the receptionist needs',
        cue: 'Confirm the booking and add the detail that matters: room, nights, name, guests or breakfast.',
        initiallyVisible: 3,
        responses: [
          { item: '000763', nuance: 'The simplest confirmation' },
          { item: '000764', nuance: 'Give room type and duration together' },
          { item: '000765', nuance: 'Describe the stay without starting with sí' },
          { item: '000766', nuance: 'Give the reservation name' },
          { item: '000767', nuance: 'Answer only the duration question' },
          { item: '000768', nuance: 'Clarify the number of guests' },
          { item: '000769', nuance: 'Clarify an included option' },
          { item: '000770', nuance: 'Handle arriving without a booking' },
        ],
      },
    ],
    spotlight: 1,
    estimatedMinutes: 10,
    learnerSpeaker: 'Cliente',
    scenarioPartner: 'the receptionist',
  },
  {
    id: 'make-plans',
    language: 'es',
    level: 'a1',
    order: 5,
    title: 'Make evening plans',
    goal: 'Suggest an activity, respond and agree on what to do.',
    passage: '700014',
    transfers: [
      {
        passage: '700019',
        support: 'guided',
        brief: 'Make a different plan for the afternoon.',
      },
      {
        passage: '700029',
        support: 'guided',
        brief: 'Suggest dinner, respond to an alternative and agree on a time.',
      },
      {
        passage: '700030',
        support: 'independent',
        brief: 'Arrange a weekend activity from intention cues and settle the details.',
      },
    ],
    capabilities: [
      'open-social-planning',
      'suggest-social-activity',
      'respond-to-suggestion',
      'coordinate-plan-time',
      'confirm-social-plan',
    ],
    responsePalettes: [
      {
        id: 'plan-reaction',
        capability: 'respond-to-suggestion',
        title: 'Accept, adjust, counter or decline',
        cue: 'Respond honestly to the suggestion. You can accept it, change one detail, offer another idea or decline politely.',
        initiallyVisible: 3,
        responses: [
          { item: '000771', nuance: 'Simple positive acceptance' },
          { item: '000772', nuance: 'Warm and enthusiastic acceptance' },
          { item: '000773', nuance: 'Casual and decisive' },
          { item: '000774', nuance: 'Accept while changing the time' },
          { item: '000775', nuance: 'Offer a preferred alternative' },
          { item: '000776', nuance: 'Give a clear practical refusal' },
          { item: '000777', nuance: 'Decline politely with a reason' },
          { item: '000778', nuance: 'Keep the relationship open' },
          { item: '000779', nuance: 'Use a softer personal refusal' },
          { item: '000780', nuance: 'Respond with a different suggestion' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 10,
    learnerSpeaker: 'Luis',
    scenarioPartner: 'a friend',
  },
  {
    id: 'morning-routine',
    language: 'es',
    level: 'a1',
    order: 6,
    title: 'Describe your morning',
    goal: 'Tell someone the main events in your morning in a connected sequence.',
    passage: '700001',
    transfers: [
      {
        passage: '700020',
        support: 'guided',
        brief: 'Describe a slower Saturday morning with a different destination.',
      },
      {
        passage: '700031',
        support: 'guided',
        brief: 'Describe a busy weekday morning with clear sequence and times.',
      },
      {
        passage: '700032',
        support: 'independent',
        brief: 'Build a connected Sunday routine from intention cues.',
      },
    ],
    capabilities: [
      'anchor-routine-in-time',
      'describe-routine-actions',
      'add-context-to-routine',
      'sequence-routine-events',
      'connect-routine-to-destination',
    ],
    responsePalettes: [
      {
        id: 'real-morning-action',
        capability: 'describe-routine-actions',
        title: 'Make the routine yours',
        cue: 'Say something true about your morning. Add a time, sequence word, place or destination when you can.',
        initiallyVisible: 3,
        responses: [
          { item: '000781', nuance: 'Anchor a habit with frequency and time' },
          { item: '000782', nuance: 'Begin a sequence clearly' },
          { item: '000783', nuance: 'Add the next action' },
          { item: '000784', nuance: 'Personalise breakfast' },
          { item: '000785', nuance: 'Add another habitual activity' },
          { item: '000786', nuance: 'Combine an action with a place' },
          { item: '000787', nuance: 'Connect an action to a time' },
          { item: '000788', nuance: 'Add destination and transport' },
          { item: '000789', nuance: 'Contrast a weekend habit' },
          { item: '000790', nuance: 'Connect events with antes de' },
        ],
      },
    ],
    spotlight: 0,
    estimatedMinutes: 9,
    scenarioPartner: 'a new friend',
  },
] as const;
